### ISSUE TITLE
authprogs appears to share many of the security holes that killed rssh

### ISSUE THREAD

**Issue by ncleaton** [daethnir/authprogs#11]
rssh (see http://www.pizzashack.org/rssh/ and https://sourceforge.net/p/rssh/mailman/rssh-discuss/ ) is a C project with similar aims to authprogs, recently dropped by its author and its debian package maintainer because it's just too hard to make it secure.

I think authprogs has some of the same problems, for example the scp rules appear to allow `scp -S /path/to/some/program` which can be used to run arbitrary commands if the attacker uploads a script.

**Comment by daethnir** [comment]
I could use specifics here.

rssh is a restricted interactive shell. It's goal was to allow users to log into a machine and have only certain commands available to it. Many of those, naturally, had the ability to exec other programs. Say you allowed someone to run 'vi' they could just "<esc>:!sh" to get a shell. Since rssh allowed a number of file transfer programs that could exec other things this was a vulnerability, such as "rsync -e /this/is/not/an/ssh/client".

authprogs similarly only allows certain commands. For example one could allow "/bin/rm /tmp/foo.txt". The commands that are allowed are either a) explicitly allowed by the account holder, or b) are commands that have built-in authprogs support.

If an account holder decides that "/usr/bin/vi" is an allowed command then it's going to be vulnerable to shell escapes, however that's not a bug in authprogs. However I think a large SECURITY section in the man page would be in order to call this out.

If the scp / rsync support in authprogs is broken and allows shell escapes then that is authprog's problem. I'm fairly certain that rsync support does not allow an escape, but I'll look at scp this weekend. The former has full command line parsing, while the later uses an denylist style rather than allowlist, and the "-S" flag likely can be abused here.

If you have additional specifics I'd love to have them.

**Comment by ncleaton** [comment]
I sent you a merge request with a couple of failing tests for the scp command restrictions.

I haven't looked in detail at your rsync stuff yet. It might be worth taking a quick look at the scp/rsync related rssh vulns to see which are applicable: https://www.cvedetails.com/product/23816/Pizzashack-Rssh.html?vendor_id=12562

**Comment by daethnir** [comment]
These should be addressed in 0.7.3 now. This does full argparse parsing so it'll reject on anything that's unexpected or explicitly disallowed.

Appreciate the report and examples.

Will leave this open for feedback.

**Comment by ceez** [comment]
Like others, I have used rssh in the past.     Knowing that there were vulnerabilities, and that it was abandon-ware, didn't leave me much reassurance.

Just curious, have you looked at GNU Rush?  I'm aware of it, but haven't really tried to deploy it.   I discovered it a couple years ago, when looking for an rssh replacement.

Concerning rsync,  it has the -s or --protect-args flag.     In this case, it passes the source and target paths through an ssh channel to the remote system, rather than as a command line argument.  Thus avoiding some (maybe most?) of the possible shell parsing problems, which would probably open the door to injection vulnerabilities.

It seems unfortunate that a similar capability doesn't exist within openssh to the args from shell interpolation.

**Comment by daethnir** [comment]
Thanks for the questions @ceez 

authprogs' rsync support uses an allowlist, so any non-supported cmdline flags are denied. -s / --protect-args is one of those. So that option is not supported (good) but also means there's no authprogs support for filenames with spaces (sad). Since it's ambiguous this was already a problem, so authprogs just throws up its hands and says "no". (Though you can work around that, if your security model allows, by using directory syncing rather than individual file syncing, since those filenames are sent over a non-ambiguous channel.)

I looked at rush a few years ago also. Has some good stuff in there. The process authorization method doesn't have any app-specific awareness though, so you need to read all the manpages for scp/rsync to know gotchas (like -s), and that's a bit of a barrier. Also scp/rsync's server-side arguments are not actually documented except in the code itself. ;-)
