### ISSUE TITLE
what is the best way to rsync userB dir/file using account userA.

### ISSUE THREAD

**Issue by oldunclez** [daethnir/authprogs#15]
For example 
the dir to backup is "/etc/userB"   owned by  userB and its permission is 700.
and authprogs is set in /home/userA/.ssh/authorized_keys 
userB is a user which does not has any login shell , such as ,www-data , gitlab ,dnsmasq and so on .  

At first , I get an idea is to :
1.  set sudoer for userA
> %userA ALL=(ALL) NOPASSWD:/usr/bin/rsync-orig
2.  replace /usr/bin/rysnc to :
```shell
#!/bin/bash
/usr/bin/sudo /usr/bin/rsync-orig "$@";
```

But it seems that authprogs will detect the /usr/bin/rsync , if it is a shell script , it will not run it .
> skipping rsync processing, binary "rsync" not in approved list

Any idea ? Thank you !

**Comment by daethnir** [comment]
authprogs in rsync mode only allows execution of /usr/bin/rsync and /usr/local/bin/rsync so as to avoid anyone getting their own version of rsync in the $PATH and circumventing security.

It does not, however, try to see what kind of program (binary, script, etc) it is.

**Comment by daethnir** [comment]
I'd caution strongly against replacing system binaries. Your operating system assumes that it owns /usr/bin/rsync. It will attempt to upgrade it when new versions are available. Stealing it is likely to break later on.

authprogs is specifically built to allow you to run a well-vetted command, under the assumption that you've limited it to activities you approve of. A specific use case is rsync as root, in fact, obviating the need to use sudo (or your proposed rsync wrapper).

So that'd be the normal pattern.

**Comment by daethnir** [comment]
Last thought: do you have a different rsync program somewhere in the default path? This might help:

ssh userA@server 'echo $PATH'
ssh userA@server 'which rsync'

Could well be that the rsync the server is picking is not /usr/bin/rsync that you were assuming. If that's the case, then you could invoke rsync from the client like this

client$ rsync --rsync-path=/usr/bin/rsync  .....

which tells rsync to request an explicit path on the server side.

**Comment by oldunclez** [comment]
> A specific use case is rsync as root, in fact, obviating the need to use sudo (or your proposed rsync wrapper).

So in my case , I should set authprogs in /root/.ssh/authorized_keys ?






> Last thought: do you have a different rsync program somewhere in the default path? This might help:
> 
> ssh userA@server 'echo $PATH' ssh userA@server 'which rsync'
> 
> Could well be that the rsync the server is picking is not /usr/bin/rsync that you were assuming. If that's the case, then you could invoke rsync from the client like this
> 
> client$ rsync --rsync-path=/usr/bin/rsync .....
> 
> which tells rsync to request an explicit path on the server side.

I am sorry . I don't quite understand it . I don't have a deifferent rsync program.
Why I replace /usr/bin/rsync to a shell script is to make sudo works , to make userA has permission to access userB dir/file .

**Comment by daethnir** [comment]
The reason I think perhaps there's another rsync is because of the authprogs error message. If there isn't, then shouldn't be an issue wrt that.

So tl;dr: yes, you should set up authprogs in /root/.ssh/authorized_keys if you want the rsync on the server to be run as root - this assures you don't create problems with the local rsync binary, while still allowing rsync as root with a very restricted set of rules.

**Comment by oldunclez** [comment]
Thank you for your opinion.



> 2. replace /usr/bin/rysnc to :
> 
> ```shell
> #!/bin/bash
> /usr/bin/sudo /usr/bin/rsync-orig "$@";
> ```
> 
> But it seems that authprogs will detect the /usr/bin/rsync , if it is a shell script , it will not run it .
> 
> > skipping rsync processing, binary "rsync" not in approved list
> 

Finally , I find out that the reason for this error .
It is because the permission for this script "/usr/bin/rsync"  is 700 , 
so it is invisible for userA , after changing it to 755 , it works.

**Comment by daethnir** [comment]
Ah, yes - when checking paths it uses shutil.which() which only matches paths that have the execute bit set for the invoking user.

So yes - authprogs was providing a custom (but possibly insufficiently detailed) error message in this case because it did not even try to run your custom /usr/bin/rsync script because it knew it would not be able to as userA.

**Comment by daethnir** [comment]
I'll close out this issue. However I'd like to reiterate my reservations about hijacking a system-supplied rsync binary. This is not stable on system upgrade, and any time you wanted to run a client rsync from this server it would run it through sudo - a normal user here couldn't even "rsync -a path1/ path1-backup/" unless they sudo access for rsync.

This isn't an authprogs bug, but might bite you later on.
